import {ITEM_IDS} from "./itemList";

export default Object.freeze([
  Object.freeze({
    displayName: "Bonnetchi",
    favoriteItems: [ITEM_IDS.DIY_SOBA, ITEM_IDS.MAGIC_SET, ITEM_IDS.TRAIN_SET, ITEM_IDS.TRUNK],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/bonnetchi.png",
    location: "Toy Park",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Charismatchi",
    favoriteItems: [ITEM_IDS.ART_CANVAS, ITEM_IDS.HAIR_DRYER, ITEM_IDS.SCOOTER, ITEM_IDS.VANITY],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/charismatchi.png",
    location: "Beauty Salon",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Cherrytchi",
    favoriteItems: [ITEM_IDS.GARDEN_KIT, ITEM_IDS.MAGAZINE, ITEM_IDS.TRAIN_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/cherrytchi.png",
    location: "Tama Farm",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Coffretchi",
    favoriteItems: [ITEM_IDS.HAIR_DRYER, ITEM_IDS.RACKET, ITEM_IDS.TRUNK, ITEM_IDS.VANITY],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/coffretchi.png",
    location: "Beauty Salon",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Goggletchi",
    favoriteItems: [ITEM_IDS.RACKET, ITEM_IDS.TRAIN_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/oyogogurutchi.png",
    location: "Gym",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Gozarutchi",
    favoriteItems: [ITEM_IDS.DIY_SOBA, ITEM_IDS.GARDEN_KIT],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/gozarutchi.png",
    location: "Gym",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Hatakemotchi",
    favoriteItems: [ITEM_IDS.GARDEN_KIT],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/hatakemotchi.png",
    location: "Tama Farm",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Kappappatchi",
    favoriteItems: [ITEM_IDS.NO_G_KIT, ITEM_IDS.STAR_ROOM],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/kappappatchi.png",
    location: "Food Town",
    gender: "M"
  }),
  Object.freeze({
    displayName: "Kikitchi",
    favoriteItems: [ITEM_IDS.SCOOTER, ITEM_IDS.UNICYCLE],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/kikitchi.png",
    location: "Tama Hotel",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Korobatchi",
    favoriteItems: [ITEM_IDS.DIY_SOBA, ITEM_IDS.FLY_CARPET, ITEM_IDS.MAGIC_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/korobatchi.png",
    location: "Magic Land",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Kuchipatchi",
    favoriteItems: [ITEM_IDS.DIY_SOBA, ITEM_IDS.FLY_CARPET, ITEM_IDS.MAGIC_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/kuchipatchi.png",
    location: "Food Town",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Kuromametchi",
    favoriteItems: [ITEM_IDS.BALL, ITEM_IDS.FLYING_DISC, ITEM_IDS.HARMONICA, ITEM_IDS.TREADMILL, ITEM_IDS.UNICYCLE],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/kuromametchi.png",
    location: "Gym",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Lovelitchi",
    favoriteItems: [ITEM_IDS.COIN_PURSE, ITEM_IDS.FORTUNE, ITEM_IDS.VANITY],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/lovelitchi.png",
    location: "Tama Hotel",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Majoritchi",
    favoriteItems: [ITEM_IDS.FORTUNE, ITEM_IDS.HARMONICA, ITEM_IDS.MAGIC_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/majoritchi.png",
    location: "Magic Land",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Mametchi",
    favoriteItems: [ITEM_IDS.FLYING_DISC, ITEM_IDS.MAGIC_SET, ITEM_IDS.PLANT_TOOLS, ITEM_IDS.STAR_ROOM, ITEM_IDS.UNICYCLE, ITEM_IDS.VR_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/mametchi.png",
    location: "Tama Hotel",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Memetchi",
    favoriteItems: [ITEM_IDS.HAIR_DRYER, ITEM_IDS.RACKET, ITEM_IDS.TRUNK, ITEM_IDS.VANITY],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/memetchi.png",
    location: "Beauty Salon",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Mochiusatchi",
    favoriteItems: [ITEM_IDS.COIN_PURSE],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/mochiusatchi.png",
    location: "Starry Lab",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Nanizatchi",
    favoriteItems: [ITEM_IDS.BINOCULARS, ITEM_IDS.NO_G_KIT, ITEM_IDS.RACKET, ITEM_IDS.STAR_ROOM],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/kiminanizatchi.png",
    location: "Starry Lab",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Nejirobotchi",
    favoriteItems: [ITEM_IDS.TRAIN_SET, ITEM_IDS.TREADMILL, ITEM_IDS.VR_SET],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/nejirobotchi.png",
    location: "Toy Park",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Nijifuwatchi",
    favoriteItems: [ITEM_IDS.FORTUNE],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/nijifuwatchi.png",
    location: "Tama Hotel",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Omechuptchi",
    favoriteItems: [ITEM_IDS.GARDEN_KIT, ITEM_IDS.MAGIC_SET, ITEM_IDS.OVEN],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/omuchaputchi.png",
    location: "Food Town",
    gender: "M",
  }),
  Object.freeze({
    displayName: "Pizalinatchi",
    favoriteItems: [ITEM_IDS.OVEN],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/pizzarinatchi.png",
    location: "Food Town",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Pompomtchi",
    favoriteItems: [ITEM_IDS.FLY_CARPET, ITEM_IDS.RACKET, ITEM_IDS.UNICYCLE],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/pompomtchi.png",
    location: "Gym",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Tuturinatchi",
    favoriteItems: [ITEM_IDS.COIN_PURSE, ITEM_IDS.FORTUNE, ITEM_IDS.RACKET, ITEM_IDS.VANITY],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/chuchurinatchi.png",
    location: "Gym",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Violetchi",
    favoriteItems: [ITEM_IDS.PLANT_TOOLS, ITEM_IDS.UNICYCLE],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/furawatchi.png",
    location: "Tama Farm",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Watawatatchi",
    favoriteItems: [ITEM_IDS.BINOCULARS, ITEM_IDS.NO_G_KIT, ITEM_IDS.RACKET, ITEM_IDS.STAR_ROOM],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/watawatatchi.png",
    location: "Tama Farm",
    gender: "F",
  }),
  Object.freeze({
    displayName: "Youmotchi",
    favoriteItems: [ITEM_IDS.ART_CANVAS, ITEM_IDS.FLYING_DISC, ITEM_IDS.HARMONICA, ITEM_IDS.PLANT_TOOLS, ITEM_IDS.TRUNK],
    imgUrl: "https://vpetparadise.com/wp-content/uploads/2019/07/youmotchi.png",
    location: "Tama Farm",
    gender: "M",
  }),
]);
